<!-- Cabecera HTML -->

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
   * {
    box-sizing: border-box;
    }
   body {
        position: relative;
        height: 100%;
        background-color: #efedea;
        font-family: scalasansot,segoe ui,roboto,helvetica neue,sans-serif;
        font-style: normal;
        color: #453f3f;
        font-size: 16px;
        line-height: 28px;
        letter-spacing: 1px;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        margin: 0;
        padding: 0;
        border: 0;
        font: inherit;
        display: block;
    }

</style>
<body>
    
    <div id="wrapper">
        <div class="header--top js-header-top-bar">
            <div class="inner-wrapper">
                <ul class="menu-top">
                    <li class="menu-top--item menu-top--item-desktop">
                        <a href="https://www.rituals.com/es-es/mag">Revista</a>
                    </li>
                    <li class="menu-top--item">
                        <a href="https://www.rituals.com/es-es/sustainability.html">Sostenibilidad</a>
                    </li>
                    <li class="menu-top--item">
                        <a href="https://www.rituals.com/es-es/faq-overview">¿Tienes alguna pregunta?</a>
                    </li>
                    <li class="menu-top--item">
                        <a href="https://www.rituals.com/es-es/stores">Localizador de tiendas</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</body>